name: dart_angular
description: Dart Angular
version: 0.0.1
environment:
  sdk: '>=2.8.1 <3.0.0'
dependencies:
  angular: ^5.3.0
  built_collection: ^4.0.0
  built_value: ^6.1.4
  built_value_generator: ^6.1.4
  json_annotation: ^3.0.0
  redux_epics: 0.10.2
  redux: ^3.0.0
  reselect: ^0.4.0
  rxdart: ^0.18.0
  meta: ^1.1.8
  less_dart: ^2.0.0
  uuid: ^2.2.2
  angular_redux:
    git:
      url: https://github.com/izolenta/angular_redux.git

dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.6.0
  build_test: ^0.10.8
  build_web_compilers: ^2.3.0
  json_serializable: ^3.2.0
  pedantic: ^1.8.0
  test: ^1.6.0
  webdev: any
